name: Deploy Mia Avatar Backend

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-flask
    
    - name: Run tests
      run: |
        pytest tests/ || echo "No tests found"
    
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t mia-avatar-backend .
    
    - name: Test Docker image
      run: |
        docker run -d -p 5001:5001 --name test-container mia-avatar-backend
        sleep 10
        curl -f http://localhost:5001/ || exit 1
        docker stop test-container
        docker rm test-container

  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to production
      run: |
        echo "Add your deployment commands here"
        echo "Examples:"
        echo "- Deploy to Heroku"
        echo "- Deploy to AWS"
        echo "- Deploy to Google Cloud"
        echo "- Deploy to Azure"

